// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigTypeGroup.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ConfigTypeGroup.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ProConfigSpace {

namespace {

const ::google::protobuf::Descriptor* ConfigTypeGroup_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ConfigTypeGroup_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ConfigTypeGroup_2eproto() {
  protobuf_AddDesc_ConfigTypeGroup_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ConfigTypeGroup.proto");
  GOOGLE_CHECK(file != NULL);
  ConfigTypeGroup_descriptor_ = file->message_type(0);
  static const int ConfigTypeGroup_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConfigTypeGroup, array_),
  };
  ConfigTypeGroup_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ConfigTypeGroup_descriptor_,
      ConfigTypeGroup::default_instance_,
      ConfigTypeGroup_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConfigTypeGroup, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConfigTypeGroup, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ConfigTypeGroup));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ConfigTypeGroup_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ConfigTypeGroup_descriptor_, &ConfigTypeGroup::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ConfigTypeGroup_2eproto() {
  delete ConfigTypeGroup::default_instance_;
  delete ConfigTypeGroup_reflection_;
}

void protobuf_AddDesc_ConfigTypeGroup_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025ConfigTypeGroup.proto\022\016ProConfigSpace\""
    " \n\017ConfigTypeGroup\022\r\n\005array\030\001 \003(\005", 73);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ConfigTypeGroup.proto", &protobuf_RegisterTypes);
  ConfigTypeGroup::default_instance_ = new ConfigTypeGroup();
  ConfigTypeGroup::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ConfigTypeGroup_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ConfigTypeGroup_2eproto {
  StaticDescriptorInitializer_ConfigTypeGroup_2eproto() {
    protobuf_AddDesc_ConfigTypeGroup_2eproto();
  }
} static_descriptor_initializer_ConfigTypeGroup_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ConfigTypeGroup::kArrayFieldNumber;
#endif  // !_MSC_VER

ConfigTypeGroup::ConfigTypeGroup()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ConfigTypeGroup::InitAsDefaultInstance() {
}

ConfigTypeGroup::ConfigTypeGroup(const ConfigTypeGroup& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ConfigTypeGroup::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ConfigTypeGroup::~ConfigTypeGroup() {
  SharedDtor();
}

void ConfigTypeGroup::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ConfigTypeGroup::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ConfigTypeGroup::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ConfigTypeGroup_descriptor_;
}

const ConfigTypeGroup& ConfigTypeGroup::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ConfigTypeGroup_2eproto();
  return *default_instance_;
}

ConfigTypeGroup* ConfigTypeGroup::default_instance_ = NULL;

ConfigTypeGroup* ConfigTypeGroup::New() const {
  return new ConfigTypeGroup;
}

void ConfigTypeGroup::Clear() {
  array_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ConfigTypeGroup::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 array = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_array:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_array())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_array())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_array;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ConfigTypeGroup::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 array = 1;
  for (int i = 0; i < this->array_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->array(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ConfigTypeGroup::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 array = 1;
  for (int i = 0; i < this->array_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->array(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ConfigTypeGroup::ByteSize() const {
  int total_size = 0;

  // repeated int32 array = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->array_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->array(i));
    }
    total_size += 1 * this->array_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ConfigTypeGroup::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ConfigTypeGroup* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ConfigTypeGroup*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ConfigTypeGroup::MergeFrom(const ConfigTypeGroup& from) {
  GOOGLE_CHECK_NE(&from, this);
  array_.MergeFrom(from.array_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ConfigTypeGroup::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConfigTypeGroup::CopyFrom(const ConfigTypeGroup& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConfigTypeGroup::IsInitialized() const {

  return true;
}

void ConfigTypeGroup::Swap(ConfigTypeGroup* other) {
  if (other != this) {
    array_.Swap(&other->array_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ConfigTypeGroup::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ConfigTypeGroup_descriptor_;
  metadata.reflection = ConfigTypeGroup_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProConfigSpace

// @@protoc_insertion_point(global_scope)
