// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigTypeGroup.proto

#ifndef PROTOBUF_ConfigTypeGroup_2eproto__INCLUDED
#define PROTOBUF_ConfigTypeGroup_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ProConfigSpace {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ConfigTypeGroup_2eproto();
void protobuf_AssignDesc_ConfigTypeGroup_2eproto();
void protobuf_ShutdownFile_ConfigTypeGroup_2eproto();

class ConfigTypeGroup;

// ===================================================================

class ConfigTypeGroup : public ::google::protobuf::Message {
 public:
  ConfigTypeGroup();
  virtual ~ConfigTypeGroup();

  ConfigTypeGroup(const ConfigTypeGroup& from);

  inline ConfigTypeGroup& operator=(const ConfigTypeGroup& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfigTypeGroup& default_instance();

  void Swap(ConfigTypeGroup* other);

  // implements Message ----------------------------------------------

  ConfigTypeGroup* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ConfigTypeGroup& from);
  void MergeFrom(const ConfigTypeGroup& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 array = 1;
  inline int array_size() const;
  inline void clear_array();
  static const int kArrayFieldNumber = 1;
  inline ::google::protobuf::int32 array(int index) const;
  inline void set_array(int index, ::google::protobuf::int32 value);
  inline void add_array(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      array() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_array();

  // @@protoc_insertion_point(class_scope:ProConfigSpace.ConfigTypeGroup)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > array_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_ConfigTypeGroup_2eproto();
  friend void protobuf_AssignDesc_ConfigTypeGroup_2eproto();
  friend void protobuf_ShutdownFile_ConfigTypeGroup_2eproto();

  void InitAsDefaultInstance();
  static ConfigTypeGroup* default_instance_;
};
// ===================================================================


// ===================================================================

// ConfigTypeGroup

// repeated int32 array = 1;
inline int ConfigTypeGroup::array_size() const {
  return array_.size();
}
inline void ConfigTypeGroup::clear_array() {
  array_.Clear();
}
inline ::google::protobuf::int32 ConfigTypeGroup::array(int index) const {
  return array_.Get(index);
}
inline void ConfigTypeGroup::set_array(int index, ::google::protobuf::int32 value) {
  array_.Set(index, value);
}
inline void ConfigTypeGroup::add_array(::google::protobuf::int32 value) {
  array_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ConfigTypeGroup::array() const {
  return array_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ConfigTypeGroup::mutable_array() {
  return &array_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProConfigSpace

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ConfigTypeGroup_2eproto__INCLUDED
