// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemShowConfig.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ItemShowConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ProConfigSpace {

namespace {

const ::google::protobuf::Descriptor* ItemShowConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ItemShowConfig_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ItemShowConfig_2eproto() {
  protobuf_AddDesc_ItemShowConfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ItemShowConfig.proto");
  GOOGLE_CHECK(file != NULL);
  ItemShowConfig_descriptor_ = file->message_type(0);
  static const int ItemShowConfig_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ItemShowConfig, show_id_),
  };
  ItemShowConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ItemShowConfig_descriptor_,
      ItemShowConfig::default_instance_,
      ItemShowConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ItemShowConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ItemShowConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ItemShowConfig));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ItemShowConfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ItemShowConfig_descriptor_, &ItemShowConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ItemShowConfig_2eproto() {
  delete ItemShowConfig::default_instance_;
  delete ItemShowConfig_reflection_;
}

void protobuf_AddDesc_ItemShowConfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::ProConfigSpace::protobuf_AddDesc_ConfigTypeGroup_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024ItemShowConfig.proto\022\016ProConfigSpace\032\025"
    "ConfigTypeGroup.proto\"!\n\016ItemShowConfig\022"
    "\017\n\007show_id\030\001 \001(\005", 96);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ItemShowConfig.proto", &protobuf_RegisterTypes);
  ItemShowConfig::default_instance_ = new ItemShowConfig();
  ItemShowConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ItemShowConfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ItemShowConfig_2eproto {
  StaticDescriptorInitializer_ItemShowConfig_2eproto() {
    protobuf_AddDesc_ItemShowConfig_2eproto();
  }
} static_descriptor_initializer_ItemShowConfig_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ItemShowConfig::kShowIdFieldNumber;
#endif  // !_MSC_VER

ItemShowConfig::ItemShowConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ItemShowConfig::InitAsDefaultInstance() {
}

ItemShowConfig::ItemShowConfig(const ItemShowConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ItemShowConfig::SharedCtor() {
  _cached_size_ = 0;
  show_id_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ItemShowConfig::~ItemShowConfig() {
  SharedDtor();
}

void ItemShowConfig::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ItemShowConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ItemShowConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ItemShowConfig_descriptor_;
}

const ItemShowConfig& ItemShowConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ItemShowConfig_2eproto();
  return *default_instance_;
}

ItemShowConfig* ItemShowConfig::default_instance_ = NULL;

ItemShowConfig* ItemShowConfig::New() const {
  return new ItemShowConfig;
}

void ItemShowConfig::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    show_id_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ItemShowConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 show_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &show_id_)));
          set_has_show_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ItemShowConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 show_id = 1;
  if (has_show_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->show_id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ItemShowConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 show_id = 1;
  if (has_show_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->show_id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ItemShowConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 show_id = 1;
    if (has_show_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->show_id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ItemShowConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ItemShowConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ItemShowConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ItemShowConfig::MergeFrom(const ItemShowConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_show_id()) {
      set_show_id(from.show_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ItemShowConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ItemShowConfig::CopyFrom(const ItemShowConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemShowConfig::IsInitialized() const {

  return true;
}

void ItemShowConfig::Swap(ItemShowConfig* other) {
  if (other != this) {
    std::swap(show_id_, other->show_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ItemShowConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ItemShowConfig_descriptor_;
  metadata.reflection = ItemShowConfig_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProConfigSpace

// @@protoc_insertion_point(global_scope)
