// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemBaseConfig.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ItemBaseConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ProConfigSpace {

namespace {

const ::google::protobuf::Descriptor* ItemBaseConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ItemBaseConfig_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ItemBaseConfig_ITEM_TYPE_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_ItemBaseConfig_2eproto() {
  protobuf_AddDesc_ItemBaseConfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ItemBaseConfig.proto");
  GOOGLE_CHECK(file != NULL);
  ItemBaseConfig_descriptor_ = file->message_type(0);
  static const int ItemBaseConfig_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ItemBaseConfig, show_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ItemBaseConfig, sell_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ItemBaseConfig, itemid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ItemBaseConfig, name_),
  };
  ItemBaseConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ItemBaseConfig_descriptor_,
      ItemBaseConfig::default_instance_,
      ItemBaseConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ItemBaseConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ItemBaseConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ItemBaseConfig));
  ItemBaseConfig_ITEM_TYPE_descriptor_ = ItemBaseConfig_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ItemBaseConfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ItemBaseConfig_descriptor_, &ItemBaseConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ItemBaseConfig_2eproto() {
  delete ItemBaseConfig::default_instance_;
  delete ItemBaseConfig_reflection_;
}

void protobuf_AddDesc_ItemBaseConfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::ProConfigSpace::protobuf_AddDesc_ConfigTypeGroup_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024ItemBaseConfig.proto\022\016ProConfigSpace\032\025"
    "ConfigTypeGroup.proto\"\274\001\n\016ItemBaseConfig"
    "\022-\n\004show\030\005 \003(\0132\037.ProConfigSpace.ConfigTy"
    "peGroup\022\014\n\004sell\030\004 \003(\005\022\016\n\006itemid\030\001 \001(\005\022\014\n"
    "\004name\030\002 \001(\t\"O\n\tITEM_TYPE\022\017\n\013ITEM_TYPE_4\020"
    "\004\022\017\n\013ITEM_TYPE_1\020\001\022\017\n\013ITEM_TYPE_2\020\002\022\017\n\013I"
    "TEM_TYPE_3\020\003", 252);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ItemBaseConfig.proto", &protobuf_RegisterTypes);
  ItemBaseConfig::default_instance_ = new ItemBaseConfig();
  ItemBaseConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ItemBaseConfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ItemBaseConfig_2eproto {
  StaticDescriptorInitializer_ItemBaseConfig_2eproto() {
    protobuf_AddDesc_ItemBaseConfig_2eproto();
  }
} static_descriptor_initializer_ItemBaseConfig_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* ItemBaseConfig_ITEM_TYPE_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ItemBaseConfig_ITEM_TYPE_descriptor_;
}
bool ItemBaseConfig_ITEM_TYPE_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ItemBaseConfig_ITEM_TYPE ItemBaseConfig::ITEM_TYPE_4;
const ItemBaseConfig_ITEM_TYPE ItemBaseConfig::ITEM_TYPE_1;
const ItemBaseConfig_ITEM_TYPE ItemBaseConfig::ITEM_TYPE_2;
const ItemBaseConfig_ITEM_TYPE ItemBaseConfig::ITEM_TYPE_3;
const ItemBaseConfig_ITEM_TYPE ItemBaseConfig::ITEM_TYPE_MIN;
const ItemBaseConfig_ITEM_TYPE ItemBaseConfig::ITEM_TYPE_MAX;
const int ItemBaseConfig::ITEM_TYPE_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int ItemBaseConfig::kShowFieldNumber;
const int ItemBaseConfig::kSellFieldNumber;
const int ItemBaseConfig::kItemidFieldNumber;
const int ItemBaseConfig::kNameFieldNumber;
#endif  // !_MSC_VER

ItemBaseConfig::ItemBaseConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ItemBaseConfig::InitAsDefaultInstance() {
}

ItemBaseConfig::ItemBaseConfig(const ItemBaseConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ItemBaseConfig::SharedCtor() {
  _cached_size_ = 0;
  itemid_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ItemBaseConfig::~ItemBaseConfig() {
  SharedDtor();
}

void ItemBaseConfig::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void ItemBaseConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ItemBaseConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ItemBaseConfig_descriptor_;
}

const ItemBaseConfig& ItemBaseConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ItemBaseConfig_2eproto();
  return *default_instance_;
}

ItemBaseConfig* ItemBaseConfig::default_instance_ = NULL;

ItemBaseConfig* ItemBaseConfig::New() const {
  return new ItemBaseConfig;
}

void ItemBaseConfig::Clear() {
  if (_has_bits_[2 / 32] & (0xffu << (2 % 32))) {
    itemid_ = 0;
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
  }
  show_.Clear();
  sell_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ItemBaseConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 itemid = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &itemid_)));
          set_has_itemid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }

      // optional string name = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_sell;
        break;
      }

      // repeated int32 sell = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_sell:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 32, input, this->mutable_sell())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_sell())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_sell;
        if (input->ExpectTag(42)) goto parse_show;
        break;
      }

      // repeated .ProConfigSpace.ConfigTypeGroup show = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_show:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_show()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_show;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ItemBaseConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 itemid = 1;
  if (has_itemid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->itemid(), output);
  }

  // optional string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->name(), output);
  }

  // repeated int32 sell = 4;
  for (int i = 0; i < this->sell_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      4, this->sell(i), output);
  }

  // repeated .ProConfigSpace.ConfigTypeGroup show = 5;
  for (int i = 0; i < this->show_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->show(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ItemBaseConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 itemid = 1;
  if (has_itemid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->itemid(), target);
  }

  // optional string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // repeated int32 sell = 4;
  for (int i = 0; i < this->sell_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(4, this->sell(i), target);
  }

  // repeated .ProConfigSpace.ConfigTypeGroup show = 5;
  for (int i = 0; i < this->show_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->show(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ItemBaseConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[2 / 32] & (0xffu << (2 % 32))) {
    // optional int32 itemid = 1;
    if (has_itemid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->itemid());
    }

    // optional string name = 2;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

  }
  // repeated .ProConfigSpace.ConfigTypeGroup show = 5;
  total_size += 1 * this->show_size();
  for (int i = 0; i < this->show_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->show(i));
  }

  // repeated int32 sell = 4;
  {
    int data_size = 0;
    for (int i = 0; i < this->sell_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->sell(i));
    }
    total_size += 1 * this->sell_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ItemBaseConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ItemBaseConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ItemBaseConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ItemBaseConfig::MergeFrom(const ItemBaseConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  show_.MergeFrom(from.show_);
  sell_.MergeFrom(from.sell_);
  if (from._has_bits_[2 / 32] & (0xffu << (2 % 32))) {
    if (from.has_itemid()) {
      set_itemid(from.itemid());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ItemBaseConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ItemBaseConfig::CopyFrom(const ItemBaseConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemBaseConfig::IsInitialized() const {

  return true;
}

void ItemBaseConfig::Swap(ItemBaseConfig* other) {
  if (other != this) {
    show_.Swap(&other->show_);
    sell_.Swap(&other->sell_);
    std::swap(itemid_, other->itemid_);
    std::swap(name_, other->name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ItemBaseConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ItemBaseConfig_descriptor_;
  metadata.reflection = ItemBaseConfig_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProConfigSpace

// @@protoc_insertion_point(global_scope)
