// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemSellConfig.proto

#ifndef PROTOBUF_ItemSellConfig_2eproto__INCLUDED
#define PROTOBUF_ItemSellConfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ConfigTypeGroup.pb.h"
// @@protoc_insertion_point(includes)

namespace ProConfigSpace {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ItemSellConfig_2eproto();
void protobuf_AssignDesc_ItemSellConfig_2eproto();
void protobuf_ShutdownFile_ItemSellConfig_2eproto();

class ItemSellConfig;

// ===================================================================

class ItemSellConfig : public ::google::protobuf::Message {
 public:
  ItemSellConfig();
  virtual ~ItemSellConfig();

  ItemSellConfig(const ItemSellConfig& from);

  inline ItemSellConfig& operator=(const ItemSellConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemSellConfig& default_instance();

  void Swap(ItemSellConfig* other);

  // implements Message ----------------------------------------------

  ItemSellConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemSellConfig& from);
  void MergeFrom(const ItemSellConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 sell_id = 1;
  inline bool has_sell_id() const;
  inline void clear_sell_id();
  static const int kSellIdFieldNumber = 1;
  inline ::google::protobuf::int32 sell_id() const;
  inline void set_sell_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ProConfigSpace.ItemSellConfig)
 private:
  inline void set_has_sell_id();
  inline void clear_has_sell_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 sell_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_ItemSellConfig_2eproto();
  friend void protobuf_AssignDesc_ItemSellConfig_2eproto();
  friend void protobuf_ShutdownFile_ItemSellConfig_2eproto();

  void InitAsDefaultInstance();
  static ItemSellConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// ItemSellConfig

// optional int32 sell_id = 1;
inline bool ItemSellConfig::has_sell_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemSellConfig::set_has_sell_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemSellConfig::clear_has_sell_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemSellConfig::clear_sell_id() {
  sell_id_ = 0;
  clear_has_sell_id();
}
inline ::google::protobuf::int32 ItemSellConfig::sell_id() const {
  return sell_id_;
}
inline void ItemSellConfig::set_sell_id(::google::protobuf::int32 value) {
  set_has_sell_id();
  sell_id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProConfigSpace

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ItemSellConfig_2eproto__INCLUDED
