// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProManagerConfig.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ProManagerConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ProConfigSpace {

namespace {

const ::google::protobuf::Descriptor* ProManagerConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ProManagerConfig_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ProManagerConfig_2eproto() {
  protobuf_AddDesc_ProManagerConfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ProManagerConfig.proto");
  GOOGLE_CHECK(file != NULL);
  ProManagerConfig_descriptor_ = file->message_type(0);
  static const int ProManagerConfig_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProManagerConfig, version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProManagerConfig, monster_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProManagerConfig, itembase_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProManagerConfig, drop_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProManagerConfig, monster_other_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProManagerConfig, itemshow_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProManagerConfig, itemsell_),
  };
  ProManagerConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ProManagerConfig_descriptor_,
      ProManagerConfig::default_instance_,
      ProManagerConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProManagerConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProManagerConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ProManagerConfig));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ProManagerConfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ProManagerConfig_descriptor_, &ProManagerConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ProManagerConfig_2eproto() {
  delete ProManagerConfig::default_instance_;
  delete ProManagerConfig_reflection_;
}

void protobuf_AddDesc_ProManagerConfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::ProConfigSpace::protobuf_AddDesc_MonsterConfig_2eproto();
  ::ProConfigSpace::protobuf_AddDesc_ItemBaseConfig_2eproto();
  ::ProConfigSpace::protobuf_AddDesc_DropConfig_2eproto();
  ::ProConfigSpace::protobuf_AddDesc_Monster_5fOtherConfig_2eproto();
  ::ProConfigSpace::protobuf_AddDesc_ItemShowConfig_2eproto();
  ::ProConfigSpace::protobuf_AddDesc_ItemSellConfig_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026ProManagerConfig.proto\022\016ProConfigSpace"
    "\032\023MonsterConfig.proto\032\024ItemBaseConfig.pr"
    "oto\032\020DropConfig.proto\032\031Monster_OtherConf"
    "ig.proto\032\024ItemShowConfig.proto\032\024ItemSell"
    "Config.proto\"\317\002\n\020ProManagerConfig\022\017\n\007ver"
    "sion\030\001 \001(\t\022.\n\007monster\030\002 \003(\0132\035.ProConfigS"
    "pace.MonsterConfig\0220\n\010itembase\030\003 \003(\0132\036.P"
    "roConfigSpace.ItemBaseConfig\022(\n\004drop\030\004 \003"
    "(\0132\032.ProConfigSpace.DropConfig\022:\n\rmonste"
    "r_other\030\005 \003(\0132#.ProConfigSpace.Monster_O"
    "therConfig\0220\n\010itemshow\030\006 \003(\0132\036.ProConfig"
    "Space.ItemShowConfig\0220\n\010itemsell\030\007 \003(\0132\036"
    ".ProConfigSpace.ItemSellConfig", 510);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ProManagerConfig.proto", &protobuf_RegisterTypes);
  ProManagerConfig::default_instance_ = new ProManagerConfig();
  ProManagerConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ProManagerConfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ProManagerConfig_2eproto {
  StaticDescriptorInitializer_ProManagerConfig_2eproto() {
    protobuf_AddDesc_ProManagerConfig_2eproto();
  }
} static_descriptor_initializer_ProManagerConfig_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ProManagerConfig::kVersionFieldNumber;
const int ProManagerConfig::kMonsterFieldNumber;
const int ProManagerConfig::kItembaseFieldNumber;
const int ProManagerConfig::kDropFieldNumber;
const int ProManagerConfig::kMonsterOtherFieldNumber;
const int ProManagerConfig::kItemshowFieldNumber;
const int ProManagerConfig::kItemsellFieldNumber;
#endif  // !_MSC_VER

ProManagerConfig::ProManagerConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ProManagerConfig::InitAsDefaultInstance() {
}

ProManagerConfig::ProManagerConfig(const ProManagerConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ProManagerConfig::SharedCtor() {
  _cached_size_ = 0;
  version_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ProManagerConfig::~ProManagerConfig() {
  SharedDtor();
}

void ProManagerConfig::SharedDtor() {
  if (version_ != &::google::protobuf::internal::kEmptyString) {
    delete version_;
  }
  if (this != default_instance_) {
  }
}

void ProManagerConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProManagerConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ProManagerConfig_descriptor_;
}

const ProManagerConfig& ProManagerConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ProManagerConfig_2eproto();
  return *default_instance_;
}

ProManagerConfig* ProManagerConfig::default_instance_ = NULL;

ProManagerConfig* ProManagerConfig::New() const {
  return new ProManagerConfig;
}

void ProManagerConfig::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_version()) {
      if (version_ != &::google::protobuf::internal::kEmptyString) {
        version_->clear();
      }
    }
  }
  monster_.Clear();
  itembase_.Clear();
  drop_.Clear();
  monster_other_.Clear();
  itemshow_.Clear();
  itemsell_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ProManagerConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string version = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->version().data(), this->version().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_monster;
        break;
      }

      // repeated .ProConfigSpace.MonsterConfig monster = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_monster:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_monster()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_monster;
        if (input->ExpectTag(26)) goto parse_itembase;
        break;
      }

      // repeated .ProConfigSpace.ItemBaseConfig itembase = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_itembase:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_itembase()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_itembase;
        if (input->ExpectTag(34)) goto parse_drop;
        break;
      }

      // repeated .ProConfigSpace.DropConfig drop = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_drop:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_drop()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_drop;
        if (input->ExpectTag(42)) goto parse_monster_other;
        break;
      }

      // repeated .ProConfigSpace.Monster_OtherConfig monster_other = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_monster_other:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_monster_other()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_monster_other;
        if (input->ExpectTag(50)) goto parse_itemshow;
        break;
      }

      // repeated .ProConfigSpace.ItemShowConfig itemshow = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_itemshow:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_itemshow()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_itemshow;
        if (input->ExpectTag(58)) goto parse_itemsell;
        break;
      }

      // repeated .ProConfigSpace.ItemSellConfig itemsell = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_itemsell:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_itemsell()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_itemsell;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ProManagerConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string version = 1;
  if (has_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->version(), output);
  }

  // repeated .ProConfigSpace.MonsterConfig monster = 2;
  for (int i = 0; i < this->monster_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->monster(i), output);
  }

  // repeated .ProConfigSpace.ItemBaseConfig itembase = 3;
  for (int i = 0; i < this->itembase_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->itembase(i), output);
  }

  // repeated .ProConfigSpace.DropConfig drop = 4;
  for (int i = 0; i < this->drop_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->drop(i), output);
  }

  // repeated .ProConfigSpace.Monster_OtherConfig monster_other = 5;
  for (int i = 0; i < this->monster_other_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->monster_other(i), output);
  }

  // repeated .ProConfigSpace.ItemShowConfig itemshow = 6;
  for (int i = 0; i < this->itemshow_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->itemshow(i), output);
  }

  // repeated .ProConfigSpace.ItemSellConfig itemsell = 7;
  for (int i = 0; i < this->itemsell_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->itemsell(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ProManagerConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string version = 1;
  if (has_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->version(), target);
  }

  // repeated .ProConfigSpace.MonsterConfig monster = 2;
  for (int i = 0; i < this->monster_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->monster(i), target);
  }

  // repeated .ProConfigSpace.ItemBaseConfig itembase = 3;
  for (int i = 0; i < this->itembase_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->itembase(i), target);
  }

  // repeated .ProConfigSpace.DropConfig drop = 4;
  for (int i = 0; i < this->drop_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->drop(i), target);
  }

  // repeated .ProConfigSpace.Monster_OtherConfig monster_other = 5;
  for (int i = 0; i < this->monster_other_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->monster_other(i), target);
  }

  // repeated .ProConfigSpace.ItemShowConfig itemshow = 6;
  for (int i = 0; i < this->itemshow_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->itemshow(i), target);
  }

  // repeated .ProConfigSpace.ItemSellConfig itemsell = 7;
  for (int i = 0; i < this->itemsell_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        7, this->itemsell(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ProManagerConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string version = 1;
    if (has_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->version());
    }

  }
  // repeated .ProConfigSpace.MonsterConfig monster = 2;
  total_size += 1 * this->monster_size();
  for (int i = 0; i < this->monster_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->monster(i));
  }

  // repeated .ProConfigSpace.ItemBaseConfig itembase = 3;
  total_size += 1 * this->itembase_size();
  for (int i = 0; i < this->itembase_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->itembase(i));
  }

  // repeated .ProConfigSpace.DropConfig drop = 4;
  total_size += 1 * this->drop_size();
  for (int i = 0; i < this->drop_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->drop(i));
  }

  // repeated .ProConfigSpace.Monster_OtherConfig monster_other = 5;
  total_size += 1 * this->monster_other_size();
  for (int i = 0; i < this->monster_other_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->monster_other(i));
  }

  // repeated .ProConfigSpace.ItemShowConfig itemshow = 6;
  total_size += 1 * this->itemshow_size();
  for (int i = 0; i < this->itemshow_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->itemshow(i));
  }

  // repeated .ProConfigSpace.ItemSellConfig itemsell = 7;
  total_size += 1 * this->itemsell_size();
  for (int i = 0; i < this->itemsell_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->itemsell(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProManagerConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ProManagerConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ProManagerConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ProManagerConfig::MergeFrom(const ProManagerConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  monster_.MergeFrom(from.monster_);
  itembase_.MergeFrom(from.itembase_);
  drop_.MergeFrom(from.drop_);
  monster_other_.MergeFrom(from.monster_other_);
  itemshow_.MergeFrom(from.itemshow_);
  itemsell_.MergeFrom(from.itemsell_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_version()) {
      set_version(from.version());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ProManagerConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProManagerConfig::CopyFrom(const ProManagerConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProManagerConfig::IsInitialized() const {

  return true;
}

void ProManagerConfig::Swap(ProManagerConfig* other) {
  if (other != this) {
    std::swap(version_, other->version_);
    monster_.Swap(&other->monster_);
    itembase_.Swap(&other->itembase_);
    drop_.Swap(&other->drop_);
    monster_other_.Swap(&other->monster_other_);
    itemshow_.Swap(&other->itemshow_);
    itemsell_.Swap(&other->itemsell_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ProManagerConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ProManagerConfig_descriptor_;
  metadata.reflection = ProManagerConfig_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProConfigSpace

// @@protoc_insertion_point(global_scope)
