
∂
DropConfig.protoProConfigSpaceConfigTypeGroup.proto"˙

DropConfig
	max_level (2
	drop_data (2.ProConfigSpace.ConfigTypeGroup

drop_count (

id (
	min_level (
rate (
	drop_type ("1
DROP_TYPE_DEFINE
FIX_DROP
RANDOM_DROP"ù
DROP_DATA_TYPE
CARDDROPTYPE
VITALITYDROPTYPE
VIPDROPTYPE
TALENTCDTIMEDROPTYPE
JIANGHUNDROPTYPE
ACHIEVEMENTPOINTDROPTYPE

ITEMDROPTYPE
COINDROPTYPE
LOYALTYDROPTYPE	
VIPEXPDROPTYPE
CARDEXPDROPTYPE
PLAYEREXPDROPTYPE
TALENTPOINTDROPTYPE
PVPPROTECTTIMEDROPTYPE
SKILLDROPTYPE
MONEYDROPTYPE
DRAGONCOMMANDDROPTYPE
EQUIPMENTDROPTYPE