local Monster_OtherConfig = {
 {
  id = 1,
  name = "武力" ,
  imageid = 3022043,
  showformat = "+%d" ,
  showformat1 = "%d" ,
  rate = 1,
  desc = "武力" ,
 },
 {
  id = 2,
  name = "智力" ,
  imageid = 3022040,
  showformat = "+%d" ,
  showformat1 = "%d" ,
  rate = 1,
  desc = "智力" ,
 },
 {
  id = 3,
  name = "统帅" ,
  imageid = 3022037,
  showformat = "+%d" ,
  showformat1 = "%d" ,
  rate = 1,
  desc = "统帅" ,
 },
 {
  id = 4,
  name = "生命" ,
  imageid = 3022039,
  showformat = "+%d" ,
  showformat1 = "%d" ,
  rate = 1,
  desc = "生命" ,
 },
 {
  id = 5,
  name = "攻击" ,
  imageid = 3022035,
  showformat = "+%d" ,
  showformat1 = "%d" ,
  rate = 1,
  desc = "攻击" ,
 },
 {
  id = 6,
  name = "武力" ,
  imageid = 3022043,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "武力" ,
 },
 {
  id = 7,
  name = "智力" ,
  imageid = 3022040,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "智力" ,
 },
 {
  id = 8,
  name = "统帅" ,
  imageid = 3022037,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "统帅" ,
 },
 {
  id = 9,
  name = "生命" ,
  imageid = 3022039,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "生命" ,
 },
 {
  id = 10,
  name = "攻击" ,
  imageid = 3022035,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "攻击" ,
 },
 {
  id = 11,
  name = "命中" ,
  imageid = 3022038,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "命中" ,
 },
 {
  id = 12,
  name = "闪避" ,
  imageid = 3022041,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "闪避" ,
 },
 {
  id = 13,
  name = "暴击" ,
  imageid = 3022036,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "暴击" ,
 },
 {
  id = 14,
  name = "韧性" ,
  imageid = 3022042,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "韧性" ,
 },
 {
  id = 15,
  name = "格挡" ,
  imageid = 3022046,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "格挡" ,
 },
 {
  id = 16,
  name = "破击" ,
  imageid = 3022045,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "破击" ,
 },
 {
  id = 17,
  name = "伤害" ,
  imageid = 3022096,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "伤害增加" ,
 },
 {
  id = 18,
  name = "减伤" ,
  imageid = 3022051,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "伤害减免" ,
 },
 {
  id = 19,
  name = "反伤" ,
  imageid = 3022052,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "反伤(固定值)" ,
 },
 {
  id = 20,
  name = "反伤" ,
  imageid = 3022052,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "伤害反弹" ,
 },
 {
  id = 21,
  name = "吸血" ,
  imageid = 3022036,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "吸血(固定值)" ,
 },
 {
  id = 22,
  name = "吸血" ,
  imageid = 3022036,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "吸血(造成伤害百分比)" ,
 },
 {
  id = 23,
  name = "吸血" ,
  imageid = 3022036,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "吸血(自身生命上限百分比)" ,
 },
 {
  id = 24,
  name = "暴伤" ,
  imageid = 3022036,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "暴击伤害增加" ,
 },
 {
  id = 25,
  name = "减暴" ,
  imageid = 3022036,
  showformat = "+%.1f%%" ,
  showformat1 = "%.1f%%" ,
  rate = 100,
  desc = "承受暴击伤害降低" ,
 },
}
return Monster_OtherConfig